name: Deployment

on:
  push:
    branches: [ "production" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag Bridger:$(date +%s)
    - name: Export Docker image to archive
      run: docker save --output "bridger-$(date +%s).tar.gz" Bridger:$(date +%s)
    - name: Copy image to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "bridger-$(date +%s).tar.gz"
        target: "bridger/"
    - name: Deploy new image to latest
      run: |
        docker load < bridger-$(date +%s).tar.gz
        docker image tag Bridger:$(date +%s) Bridger:latest
        
      
